name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.5

environment:
  sdk: ^3.8.1

dependencies:
  build_runner: ^2.6.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  http: ^1.5.0
  url_launcher: ^6.3.2
  package_info_plus: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.7.2
  permission_handler: ^12.0.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
